version: "3"

services:
  app:
    image: mattermost/focalboard:0.8.0 
    container_name: focalboard
    depends_on:
      - focalboard-db
    ports:
      - 8000:8000
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
    volumes:
      - "./config.json:/opt/focalboard/config.json"
    restart: always
    networks:
      - focalboard

  focalboard-db:
    image: postgres:12.7
    restart: always
    container_name: focalboard-postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password
    networks:
      - focalboard

networks:
  focalboard:
