version: '3'
services:
  portainer:
    container_name: portainer
    image: /portainer:1.24.2-alpine
    volumes:
      - ./portainer_data:/data
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
